EU-76
anton-serozhechkin/e_university_api pull request #82
Opened 2022-11-11 18:57 UTC by YehorVoitenko

2022-11-11 18:58 UTC, YehorVoitenko commented
https://euniversity.atlassian.net/browse/EU-76

2022-11-13 20:39 UTC, DmytroLyt approved these changes, later dismissed

2022-11-13 20:42 UTC, anton-serozhechkin requested changes

2022-11-13 20:42 UTC, anton-serozhechkin commented on Dockerfile
> +RUN poetry install --with test,lint,parcing,documents,security,database,main
we need only main module by defauly, bcs test and lint will be included in future tickets

2022-11-13 20:42 UTC, anton-serozhechkin commented on pyproject.toml
>  [tool.poetry.dependencies]
union parcing, documents, security, and database module in this one

2022-11-13 21:37 UTC, anton-serozhechkin submitted a review, later dismissed

2022-11-14 11:08 UTC, DmytroLyt submitted a review, later dismissed

2022-11-14 23:15 UTC, anton-serozhechkin approved these changes

2022-11-14 23:16 UTC, merged